title:            Blade extensions
description:      Extensions for Laravel blade templating. Implements loop data and break/continue in foreach directive. View partials and blocks. Setting and unsetting of variables. Macros and debug.
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url: http://robinradic.github.io


layouts:     ./_includes/_layouts
data_source:  ./_includes/_data



# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Amsterdam/Netherlands
future:      true

highlighter: pygments
kramdown:
  input: GFM

sass:
  sass_dir: _sass
  style: compressed
